# Generated by Django 3.0.5 on 2020-04-16 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_num', models.CharField(max_length=15)),
                ('staff_station', models.CharField(max_length=20)),
                ('ticket_category', models.CharField(choices=[('internet', 'Internet'), ('procamis', 'PROCAMIS'), ('software', 'Software'), ('hardware', 'Hardware'), ('others', 'Others')], max_length=10)),
                ('ticket_description', models.TextField(max_length=100)),
                ('ticket_number', models.CharField(default=True, max_length=100)),
                ('ticket_status', models.CharField(choices=[('open', 'Open'), ('progress', 'Progress'), ('closed', 'Closed')], max_length=10)),
                ('ticket_priority', models.CharField(choices=[('neutral', 'Neutral'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10)),
                ('action_taken', models.TextField(max_length=100)),
                ('officer_handling', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='when created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='when updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
