# Generated by Django 3.0.5 on 2020-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='action_taken',
            new_name='current_condition',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='ticket_description',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='staff_station',
            new_name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='officer_handling',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ticket_category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ticket_priority',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ticket_status',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_description',
            field=models.TextField(default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('PROCAMIS', 'PROCAMIS'), ('SOFTWARE', 'SOFTWARE'), ('HARDWARE', 'HARDWARE'), ('OTHERS', 'OTHERS')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='recommendation',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'Progress'), ('ready', 'Ready'), ('taken', 'Taken')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='user_assesment',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
