# Generated by Django 3.0.5 on 2020-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200416_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=50),
        ),
    ]
