# Generated by Django 3.0.5 on 2020-04-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200416_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_num',
        ),
    ]
