# Generated by Django 3.0.5 on 2020-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_equipment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('Monitor', 'MONITOR'), ('Printer', 'PRINTER'), ('UPS', 'POWER SUPPLY'), ('Others', 'OTHERS')], max_length=20),
        ),
    ]
