# Generated by Django 3.0.5 on 2020-04-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20200416_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_description',
        ),
    ]
