# Generated by Django 3.0.5 on 2020-04-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipment_equipment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='user',
        ),
    ]
