# Generated by Django 3.0.5 on 2020-04-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='user',
        ),
    ]
