# Generated by Django 3.0.5 on 2020-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_auto_20200417_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='when updated'),
        ),
    ]
