# Generated by Django 3.0.5 on 2020-04-23 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=100)),
                ('ticket_category', models.CharField(choices=[('procamis', 'procamis'), ('internet', 'internet'), ('hardware', 'hardware'), ('software', 'software'), ('others', 'others')], max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('resolved', 'resolved'), ('closed', 'closed')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('nuetral', 'nuetral'), ('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], default='neutral', max_length=100)),
                ('action_taken', models.CharField(choices=[('open', 'open'), ('prossesing', 'prossesing')], default='open', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
