# Generated by Django 2.2.7 on 2020-05-07 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=100)),
                ('ticket_category', models.CharField(choices=[('procamis', 'procamis'), ('internet', 'internet'), ('hardware', 'hardware'), ('software', 'software'), ('others', 'others')], max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('resolved', 'resolved'), ('closed', 'closed')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('nuetral', 'nuetral'), ('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], default='neutral', max_length=100)),
                ('action_taken', models.TextField(max_length=100, null=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('technician', models.ForeignKey(default='General', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
    ]
