# Generated by Django 3.0.5 on 2020-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='technician',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
