# Generated by Django 3.0.5 on 2020-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='action_taken',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
