# Generated by Django 2.2.7 on 2020-05-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200507_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketstatus',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketStatus'),
        ),
    ]
