# Generated by Django 2.2.7 on 2020-05-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20200507_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_status',
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
